batch_size: 16
cuda: true
dataset_keys: ["actions", "rewards", "dones"]
goal_mode: null
hdf5_cache_mode: "low_dim"
hdf5_filter_key: null
hdf5_normalize_obs: false
hdf5_use_swmr: true
num_data_workers: 0
num_epochs: 1000
seed: 1
seq_length: 1
