core_class: ScanCore
core_kwargs:
  conv_activation: relu
  conv_kwargs:
    kernel_size: [32, 64, 64]
    out_channels: [32, 64, 64]
    stride: [4, 2, 1]
  feature_dimension: 64
  flatten: true
  pool_class: SpatialSoftmax
  pool_kwargs:
    learnable_temperature: false
    noise_std: 0.0
    num_kp: 32
    output_variance: false
    temperature: 1.0
